### ISSUE TITLE
12.0 Enforce entry of Internal Order and Project Start date

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2380]
The current project lifecycle is something like:
Application -> Active -> Completed/Terminated.

The transition from Application -> Active happens when the project MERI plan is approved for the first time.  At the time of approval, the project internal order number must be supplied.

Project reports are currently generated when the project is loaded based on the supplied project start date.  However, the actual start date is often not known at this time.  This can result in the situation where project reports are completed before the project officially starts, which results in a messy process to modify the start date without compromising report data.

The main benefit of this change is to prevent the above situation by deferring the creation of project reports until a correct start date has been negotiated.
Another item that will be addressed is to attempt to improve the capture of the project internal order number which is sometimes entered as TBA and not later updated.

The proposed workflow is:
1) At the time of approving the MERI plan for the first time, the project/grant manager will be given the opportunity to update the project start date.  As it does now, at this point the project status transitions to "Active"
2) The grant manager will then be required to explicitly trigger the generation of the project reporting schedule.  At the point of generating these reports, another opportunity will be given to update the start date.
3) Once any report contains data the start date can no longer be changed 

To implement this change, the following changes are required to MERIT:
- [x] Do not generate reports when a project is loaded.
- [x] Do not generate reports during merit plan approval
- [x] Do not allow reports to be generated for a project unless the status is "Active"
- [x] Add a field to update the project start date to the MERI Plan Approval dialog where the order number is currently specified.
- [x] Change the validation of the internal order number so it contains all numeric characters
- [x] For projects that are active, but do not have any data in any reports (or no reports), include a button at the top of the Reporting tab that, when pressed behaves similarly to the MERI approval dialog in that it allows for the entry of the project start date (pre-populated to the current values) and a button to save and generate the reports.  
- [ ] https://github.com/AtlasOfLivingAustralia/fieldcapture/issues/2548

**Comment by chrisala** [comment]
To implement this change, the following changes are required to MERIT:
1) Do not generate reports when a project is loaded.
2) Do not allow reports to be generated for a project unless the status is "Active"
3) Add a field to update the project start date to the MERI Plan Approval dialog where the order number is currently specified.
4) Change the validation of the internal order number to match the format so that PDF
5) For projects that are active, but do not have any data in any reports (or no reports), include a button at the top of the Reporting tab that, when pressed behaves similarly to the MERI approval dialog in that it allows for the entry of an internal order number and start date (pre-populated to the current values) and a button to save and generate the reports.
