### ISSUE TITLE
15.0 Amend ROLE_FC_READ_ONLY role

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2401]
Item 15.0 on the work plan.

- [x] Allow read only users to view and download project reports #2260 
- [x] Allow read only users to view management unit tabs and reports #2385 
- [x] Allow read only users to view the "Project Access" tab on the Project and Management Unit admin tab #2505 
- [x] Allow read only users to view all management unit documents #2516 
- [x] Allow read only users to view and use the "Audit" section on the Project admin tab #1019
- [x] Create a view mode for the data set summary and allow read only users to access it #2386 
- [x] #2427 
- [x] #2511 
- [x] Allow read only users to download shapefile https://github.com/AtlasOfLivingAustralia/fieldcapture/issues/2519
