### ISSUE TITLE
11.0 Bulk download of MERIT data

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2406]
- [x] Create a mechanism to schedule report downloads (could just be cron as this is mostly temporary) #2457 
- [x] Add a configuration parameter that will produce downloads with a single header row containing only property names.  The default should be to keep the current format.  This doesn't need to be included on the UI as it will be used by the scheduled/cron job above.
- [x] Implement a data dictionary to record metadata about any fields exposed in the API and/or download.
- [x] #2482
- [x] Improve the ability to select reports for download #1776 
- [x] #2463
- [x] Configure the set of downloads to be run weekly
