### ISSUE TITLE
2.0 Spatial Data Upload Fixes

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2408]
Implement a new system of spatial file upload, with improved ability for users to “fix” files prior to upload.

- [ ] Identify all large spatial files stored in MERIT (>2GB?), conduct remediation/fixes to reduce the files size below a certain threshold.
- [ ] Replace existing spatial data upload system. New system should not allow “large” spatial files to be uploaded – but gives the opportunity to correct them 
- [ ] Give users an opportunity to correct spatial files (e.g. enclose unclosed polygons) at the point of upload.

**Comment by chrisala** [comment]
Related issues:
* #1815 
* #2078 
* #1736 
* #1734
