### ISSUE TITLE
1.1 Transfer user management into MERIT

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#2414]
The global CAS roles FC_ADMIN, FC_OFFICER and FC_READ_ONLY are more accurately modelled as roles on the MERIT hub.  Hub roles are already implemented for BioCollect, so this task will leverage the work done for BioCollect.
 
- [x] Introduce a new role/accessLevel "readOnly" in ecodata and MERIT. #2420
- [x] Implement a user interface to add / remove these roles on the MERIT hub. #2419
- [x] #2422
- [x] #2423
- [x] #2421
- [x] Update the administrator user list report as required so that it continues to work correctly after this change AtlasofLivingAustralia/ecodata#704
